### ISSUE TITLE
The required validator always return "Value is required" if the input type is not a string

### ISSUE THREAD

**Issue by QuentinPom** [shibayan/Sharprompt#103]
The `Validators.Required()` can be added to input on a type different than string.

The `Required` validators only check string attributes and return `Value is required` if the type is different than a string, even if the value is correct.

![image](https://user-images.githubusercontent.com/42981614/107830133-34c86f80-6d59-11eb-9fae-6cf506646426.png)

Solution:
Update the `Required` validator by adding a check on a type different than string.
https://github.com/shibayan/Sharprompt/blob/2a8c885835b590b831ac4007e6a70108f10c393d/Sharprompt/Validators.cs#L9-L19

**Comment by shibayan** [comment]
Thanks for the feedback. This was a complete mistake on my part. It will be fixed shortly.

For reference, for value types such as int, you can use nullable to determine whether it is required or not.
```csharp
// required value
var integer = Prompt.Input<int>("Enter an integer");

// allow null value
var integerOrNull = Prompt.Input<int?>("Enter an integer");
```
