### ISSUE TITLE
Exception in Prompt.Select<MyEnum> if DispalyName.Order is not set

### ISSUE THREAD

**Issue by penenkel** [shibayan/Sharprompt#113]
With #82 the following regression was introduced:

When using `Prompt.Select<MyEnum>("My Prompt")`. I.e. with the automatic choice generation from enums. 
When the Enum fields are decorated with `Display(Name="choice display text")` but the `Order` parameter is *not* specified, the code will fail with:

> The Order property has not been set.  Use the GetOrder method to get the value

Apparently one is not supposed to use `displayAttribute.Order` if the Order field has not been explicitly set.
[referencesource](https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/System.ComponentModel.DataAnnotations/DataAnnotations/DisplayAttribute.cs#L286)

This should be an easy fix in [EnumValue.cs](https://github.com/shibayan/Sharprompt/blob/bb8a2de8ce609475c42b7a19c2e8f95c6d4fdbf3/Sharprompt/Internal/EnumValue.cs#L17)

**Comment by shibayan** [comment]
Thanks for the bug report. A fix will be in place soon.

**Comment by penenkel** [comment]
Wow, 30min from report to fix and only 2h to release, impressive 🥇. Thank you.
