### ISSUE TITLE
Adding a new List prompt

### ISSUE THREAD

**Issue by ryfu-msft** [shibayan/Sharprompt#118]
Hey @shibayan,

I had a idea to build a List form input that would take in values and append them to an existing list. For example:

What would you like to add to your grocery list? : Banana
- Apple
- Orange

Pressing ENTER would append Banana to the end of this list and ask again. 

What would you like to add to your grocery list? : 
- Apple
- Orange
- Banana

If the user presses ENTER without any value, the prompt would end.

Please let me know what you think and if you like it, I would like to try working on this.

**Comment by shibayan** [comment]
I'm a little confused about how it works, is it an additional feature to `Prompt.Select`?

**Comment by ryfu-msft** [comment]
It could be an additional feature to `Prompt.Select` or a standalone prompt. My thinking was that it could address the scenario where a single question requires multiple inputs from the user. Rather than trying to list all the inputs in a single line response, it would append multiple responses to a list that a user could see.

**Comment by shibayan** [comment]
I understand most of it. I will present the code based on my understanding.

```csharp
// Accept Prompt.Input user-input
// typeof(picked) == IEnumerable<string>
var picked = Prompt.List<string>("Please add item(s)", minimum: 1, maximum: 3);

Cobsole.WriteLine(string.Join(",", picked));
```

**Comment by palenshus** [comment]
That looks good! Hopefully we'd still be able to pass `IList<Func<object, ValidationResult>> validators` as well, which could internally be applied to each item in the enumerable.
