### ISSUE TITLE
Pasting large text in prompt causes slow rendering and flickering

### ISSUE THREAD

**Issue by ryfu-msft** [shibayan/Sharprompt#120]
I believe that this might be related to #80, but when pasting an extremely large text into the prompt, The words are rendered slowly and the console begins flickering until all of the characters are visible. 

Repro steps:
- Copy text with greater than ~300 words
- When prompt appears in console, paste text as response.

[Prompt] What is your name? : <Insert large text>

Behavior:
- Repeated flickering of the console while the words are being rendered.
- Rendering is slower than normal until all words from the pasted text are visible.

**Comment by shibayan** [comment]
This issue has been fixed in `v2.3.0-preview2`. Thanks.
