### ISSUE TITLE
Support for cancellable prompts, two new controls and many enhancement

### ISSUE THREAD

**Issue by FRACerqueira** [shibayan/Sharprompt#135]
This fork (https://github.com/FRACerqueira/Sharprompt) at master  
adds support for cancellable prompts, two new controls and many enhancement 

Resume:
- Support Cancelation Token for all promts (enhancement)
- Custom Prompter custom messages for all promts (enhancement)
- Revised behavior/navigator of all prompts with Interative result (enhancement)
- Prompt List with support to remove item and paging (enhancement)
- Prompt Anykey (new - Simple any key-press)
- Prompt FileBrowser (new - Browser file/folder) 

Preview prompts :

![Prompt_FileBrowser](https://user-images.githubusercontent.com/45797410/127404468-80f032b3-20b7-4487-8ad9-2d369722fde2.gif)

![Prompt_FolderBrowser](https://user-images.githubusercontent.com/45797410/127404472-7a3b20f6-b289-4cbe-a557-59c43a5f52f1.gif)

![Prompt_Input](https://user-images.githubusercontent.com/45797410/127404473-7da42dc5-6fb5-40d1-8dc6-bc9eea597018.gif)

![Prompt_List](https://user-images.githubusercontent.com/45797410/127404475-1b37dfc1-cf57-4499-86e1-0cf58f57e9f1.gif)

![Prompt_MultSelect](https://user-images.githubusercontent.com/45797410/127404477-97977c7e-b3f1-4356-8494-20d1140ad984.gif)

![Prompt_Password](https://user-images.githubusercontent.com/45797410/127404478-7ab9e837-cd08-4cc9-b5ca-e2b38bde7a98.gif)

![Prompt_Select](https://user-images.githubusercontent.com/45797410/127404481-acb46506-7779-4c48-b96d-d5c47a3741fe.gif)

![Prompt_Confirm](https://user-images.githubusercontent.com/45797410/127404482-99ce27c9-9f9f-4386-a45a-c981975ef058.gif)

![Prompt_EnumMultSelect](https://user-images.githubusercontent.com/45797410/127404483-e053dce4-521c-4f19-b853-78734cc68836.gif)

![Prompt_EnumSelect](https://user-images.githubusercontent.com/45797410/127404485-a7eb9d91-5deb-4b20-a28a-6bb17b1059bd.gif)

**Comment by shibayan** [comment]
https://www.igvita.com/2011/12/19/dont-push-your-pull-requests/
