### ISSUE TITLE
Support Prompt.Input<Guid>

### ISSUE THREAD

**Issue by kimsey0** [shibayan/Sharprompt#155]
It would be useful to be able to read GUIDs like:
```csharp
var resourceId = Prompt.Input<Guid>("Please enter resource ID");
```

However, this fails since `Convert.ChangeType` can't convert from `string` to `Guid` at
https://github.com/shibayan/Sharprompt/blob/c64259bc88c27867d2265094406b0520dc359af1/Sharprompt/Internal/TypeHelper.cs#L12

It might perhaps be implemented by instead using [`TypeDescriptor.GetConverter(_underlyingType ?? _targetType).ConvertFrom(value)`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typedescriptor.getconverter) or `TypeDescriptor.GetConverter(_underlyingType ?? _targetType).ConvertFromInvariantString(value)`, which would then delegate to [GuidConverter](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.guidconverter) for GUIDs, though the effect on other types, like floating point numbers, would of course have to be considered.

**Comment by shibayan** [comment]
Thank you. This change looks good to me.

**Comment by shibayan** [comment]
It has been improved to `v2.3.3`. Thank you!

**Comment by kimsey0** [comment]
Thank you!
