### ISSUE TITLE
Unable to paste into console

### ISSUE THREAD

**Issue by tombly** [shibayan/Sharprompt#161]
Starting with release 2.3.3, we're no longer able to copy-and-paste text into the console. When you try to do it, the prompt just stays empty. Thanks!

**Comment by shibayan** [comment]
I was not able to reproduce this problem. Pasting to the console works in my environment.

**Comment by tombly** [comment]
Thanks for the quick reply. In case you're interested, we're seeing it when we run a .NET Core console app via Visual Studio 2019 in Windows 10. Maybe just something to keep an eye out for. Thanks for the helpful project!

**Comment by hhoangnl** [comment]
I have the same issue. I have been starting to use this library since 2.4.1
I have a .NET Core console app, too.
