### ISSUE TITLE
TextSelector parameter for MultiSelect doesn't work

### ISSUE THREAD

**Issue by yskkmr** [shibayan/Sharprompt#163]
TextSelector parameter for `MultiSelect<T>` doesn't work. One for `Select<T>` works well. 
I think this can be resolved to fix in Prompt.Basic.cs. 
https://github.com/shibayan/Sharprompt/blob/afaa7901571311c17e93fcbacdc61bc7381c8961/Sharprompt/Prompt.Basic.cs#L188

Thanks!

**Comment by shibayan** [comment]
Thanks for the report. This is obviously a bug and will be fixed soon.

**Comment by shibayan** [comment]
This has been fixed in `v2.3.4`. Thanks!
