### ISSUE TITLE
Configurable strings for prompt messages/keys

### ISSUE THREAD

**Issue by IbexPeak** [shibayan/Sharprompt#207]
Hi shibayan,

it would be nice if the keys and the displayed messages for a prompt are configurable. So that the key "y/n" and the messages "yes"/"no" can be configured at the static Prompt class.

This allows us defining localizable inputs, as in Germany we usually use "J/N" and "Ja"/"Nein" without forking the repo as we do now.

Thanks!

**Comment by diegosps** [comment]
Hi, shibayan!
I'm having trouble understanding how to localize my local application. 
Is the only available way doing a PR with the complete resource.XX.resx to be added in the main project?
Or can I set an incomplete resource file at my project and somehow make sharprompt consume it for the entries that I set?

Thanks!

**Comment by IbexPeak** [comment]
Would be interesting for me too

**Comment by shibayan** [comment]
Localized resources can be merged after a brief review by me using machine translation if you create a PR.
