### ISSUE TITLE
How make it is runing Framework 3.5 ?

### ISSUE THREAD

**Issue by zoucap** [shibayan/Sharprompt#215]
I down the source code and build a Class library that name is "Sharprompt.dll".I import it to my project, and tell me some erroes.
What can I do to solve this problem？
![errors](https://user-images.githubusercontent.com/61569956/167289992-c22a7e9c-dc25-495a-a187-74e44927fd1d.png)

**Comment by shibayan** [comment]
This library is not supported .NET Framework 3.5.

You will need to update to a version supported by the following documentation.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0
