### ISSUE TITLE
Sharprompt breaks `Console.CancelKeyPress`

### ISSUE THREAD

**Issue by justinmchase** [shibayan/Sharprompt#219]
If I never show the prompt then my ctrl+c cancel handler works, but if I show the prompt then it stops working.

My cancellation handler in program.cs
```cs
      Console.CancelKeyPress += (object? sender, ConsoleCancelEventArgs e) =>
      {
        Console.ForegroundColor = ConsoleColor.DarkYellow;
        Console.Write($"Interrupted");
        Console.ResetColor();
        Console.WriteLine();

        if (command != null)
        {
          this.tokenSource.Cancel();
          e.Cancel = true;
        }
      };
```

My prompt
```cs
      var kinds = Prompt.MultiSelect<BuildKind>(
        "Please specify a build kind:",
        new[] {
            BuildKind.docker,
            BuildKind.helm,
            BuildKind.node,
            BuildKind.dotnet,
            BuildKind.java
        }
      );
```

If I just comment out the kind and hard code one, then the cancellation works as expected.

Is there something happening in Prompt that can be unset to return cancellation behavior?

**Comment by justinmchase** [comment]
So here basically:
https://github.com/shibayan/Sharprompt/blob/a5999f6029c670de957fb388759016bec7e41d9d/Sharprompt/Drivers/DefaultConsoleDriver.cs#L18

It seems like in the dispose method it needs to set it back, but not to false blindly but rather to what it was before the default console driver took control.

**Comment by shibayan** [comment]
Thanks for the feedback. You are right, I need to restore the previous state correctly.
