### ISSUE TITLE
Request new release with German localization

### ISSUE THREAD

**Issue by IbexPeak** [shibayan/Sharprompt#235]
Hi Shibayan,

as you know I recently integrated the German translation into Sharprompt, which was merged some days ago.

Our project needs this feature as soon as possible, so I want to kindly ask if you can create a new release? That would be great, thanks!

Greetings, IbexPeak

**Comment by shibayan** [comment]
It will be released this month.

**Comment by IbexPeak** [comment]
Thank you very much :)
