### ISSUE TITLE
Resizing new Windows Terminal during active selection prompt causes exception

### ISSUE THREAD

**Issue by Spiritreader** [shibayan/Sharprompt#247]
## Description

When
- using the Windows terminal app on W10 and W11 or alternatively
- having it set as default CMD window in Win11

reducing the terminal size and initiating a navigation afterwards via the keyboard will cause an inner exception indicating an issue with the currently set terminal cursor position.

It does work fine with the legacy terminal, so I think there were some changes made to how the terminal updates the active number of lines after a resize event.
I believe that sharprompt is not aware of this change yet, which why it fails to work with resizing.

Unfortunately, when launching a terminal and the window is initially too small for the text to fit, it also crashes.
This usually happens when there is a scaling factor applied in Windows.

### Exception Data

```
Unhandled exception. System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 29.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Sharprompt.Drivers.DefaultConsoleDriver.SetCursorPosition(Int32 left, Int32 top)
   at Sharprompt.Drivers.DefaultConsoleDriver.ClearLine(Int32 top)
   at Sharprompt.Internal.OffscreenBuffer.ClearConsole(Int32 cursorBottom, Int32 writtenLineCount)
   at Sharprompt.Internal.RenderScope.Dispose()
   at Sharprompt.Forms.FormRenderer.Render(Action`1 template)
   at Sharprompt.Forms.FormBase`1.Start()
   at Sharprompt.Prompt.Select[T](SelectOptions`1 options)
   at Sharprompt.Prompt.Select[T](Action`1 configure)
   at Sharprompt.Prompt.Select[T](String message, IEnumerable`1 items, Nullable`1 pageSize, Object defaultValue, Func`2 textSelector)
   at AutoDarkModeComms.Program.Main(String[] args) in D:\Code\Repos\AutoDarkMode\Windows-Auto-Night-Mode\AutoDarkModeShell\Program.cs:line 77
```

### Analyzing the origin

https://github.com/shibayan/Sharprompt/blob/4544d1999caea3f32a13af8ab541374a82f97475/Sharprompt/Drivers/DefaultConsoleDriver.cs#L96

Since it's this method and the exception complains about the `top` parameter, it tracks back to the `ClearLineMethod` in the console driver.

https://github.com/shibayan/Sharprompt/blob/4544d1999caea3f32a13af8ab541374a82f97475/Sharprompt/Internal/OffscreenBuffer.cs#L101

The `OffscreenBuffer` class determines the `top` position via the cursor bottom position and the written lines.
I would assume when the console dimensions change externally, the `writtenLineCount` and `cursorBottom` no longer accurately reflect the console state which is the cause of the exception.

### More Details

The line causing the issue in my code is 
```c#
Prompt.Select("Select a command", fields);
```

[Link to project where Prompt.Select is called](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/blob/224926d51107fefd68c64c9d1087af448fa33995/AutoDarkModeShell/Program.cs#L77)

I don't believe I configured sharprompt wrong to cause this, but I've included where the exception is coming from on my end, just to be safe.

## What I've tried

Catching the `ArgumentOutOfRangeException` and restarting the prompt works for my specific case. Unfortunately, this also resets the selected entry.
I'm not sure if this intended behavior. because it requires users to call `Prompt.Select` whenever it throws an exception related to terminal resizing events.

In case this is intended, it would maybe be helpful to add to the inline or github doc that the exception needs to be caught if terminal resizing is expected with newer terminal versions.

[Link to fix in my project](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/blob/f34801f1a33f59188523155ac9dd566c04aee163/AutoDarkModeShell/Program.cs#L81)

## Video

I've attached a video to give further context to the issue recorded on my desktop. As it has no scaling factor set and I discovered the scaling issue on my laptop, I was unfortunately unable to show the issue when initially opening the cmd window.

https://user-images.githubusercontent.com/18438899/203457860-62104a45-6854-4ae1-99cc-9bf22f6a04a1.mp4

**Comment by shibayan** [comment]
Sorry for the delay in response.

The root cause of this problem is that the Windows Terminal, unlike the Legacy Terminal, has been modified to reserve the buffer size equal to the window size. And since Windows Terminal does not provide events on resizing, the application cannot detect the change.

This results in the exception you reported when the size is reduced. We have identified the cause of the problem and are attempting to fix it.
