### ISSUE TITLE
Show a distinction in selected items in MultiSelect

### ISSUE THREAD

**Issue by aikoofujimotoo** [shibayan/Sharprompt#60]
This makes it harder to tell which are selected and which are not.
![image](https://user-images.githubusercontent.com/35658068/86362192-dbbb3800-bcaf-11ea-9d28-4c40ce493a52.png)

**Comment by shibayan** [comment]
Please share your environment (e.g. OS / shell type).

**Comment by aikoofujimotoo** [comment]
OS: Windows 10 Pro Build 2004 (19041.329)

**Comment by shibayan** [comment]
I couldn't reproduce it.
