### ISSUE TITLE
Don't delete text input when it fails validation

### ISSUE THREAD

**Issue by kimsey0** [shibayan/Sharprompt#75]
If using for example the `MinLength` validator with a decently large minimum length, you might type a long, but not quite long enough, sentence, click Enter, then get an error message saying the _Value is too short_, then see your message deleted and have no way to recover it.

The user experience here could be improved if, after showing the error message, either the entered value is kept or it is possible to recover it in some way, for example by clicking the up arrow, like in most command line interfaces.

**Comment by shibayan** [comment]
Thanks for the feedback. You're right, it's definitely not user-friendly to have the input text deleted on validation failure.

I am working to improve this behavior.
