### ISSUE TITLE
Navigating to previous prompts

### ISSUE THREAD

**Issue by ryfu-msft** [shibayan/Sharprompt#91]
I currently have a loop that asks a series of prompts. I want to have a way to return to a previous prompt even when answering the current prompt in case a user realizes that one of the past responses was incorrect. How would I go about doing this? Does Sharprompt support historical navigation?

**Comment by shibayan** [comment]
As for the user flow, we think it is difficult to implement because there is currently no way to cancel it.

As for me, I would like to discover the possibility of realizing this by defining the user flow in AutoForms.

**Comment by shibayan** [comment]
I think this can be done in the user code since the application can now handle the cancellation in PR #150.

I looked into some commonly used interactive CLI tools, but it seems that the ability to go back one step itself is often not implemented. There would be no shortcut keys either.
