### ISSUE TITLE
Weird behavior on Windows terminals

### ISSUE THREAD

**Issue by RoganMatrivski** [shibayan/Sharprompt#94]
The new interface for the prompt seems to broke my terminals, especially the one that doesn't have a unicode support.
It produces this weird character on the beginning of the line after I type the answer, or submitting the answer.
![image](https://user-images.githubusercontent.com/19743747/105177308-15bf2f00-5b59-11eb-98d3-d73e87e64523.png)

It also occurs on Powershell 7
![image](https://user-images.githubusercontent.com/19743747/105177425-3e472900-5b59-11eb-9b1a-ed69ba2442c0.png)

The code was a simple yes/no input and the usual input
``` C#
using Sharprompt;
using System;

namespace ConsolePlayground
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var confirmOverwrite = Prompt.Confirm("Existing configuration already exists! Overwrite file?", false);
            if (!confirmOverwrite) return;
            var Testvar1 = Prompt.Input<string>("Input a string");
            var Testvar2 = Prompt.Password("Input another string");
        }
    }
}
```

Also, here's the video demo about the issue.

https://user-images.githubusercontent.com/19743747/105180263-e90d1680-5b5c-11eb-9c2c-d66f40547817.mp4

**Comment by shibayan** [comment]
Thanks for the report.

I'll fix it, as I had to explicitly enable the flag to use VT100 in the normal terminal.
